version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: aidareu_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: aidareu
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/postgres-202510081508.sql:/docker-entrypoint-initdb.d/restore.sql
    networks:
      - aidareu_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Laravel Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: aidareu_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      APP_NAME: Aidareu
      APP_ENV: production
      APP_KEY: base64:YOUR_APP_KEY_HERE
      APP_DEBUG: false
      APP_URL: https://api.aidareu.com

      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: aidareu
      DB_USERNAME: postgres
      DB_PASSWORD: postgres

      CACHE_STORE: database
      QUEUE_CONNECTION: database
      SESSION_DRIVER: database

      SANCTUM_STATEFUL_DOMAINS: aidareu.com,www.aidareu.com
      SESSION_DOMAIN: .aidareu.com
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./backend/storage:/var/www/html/storage
    networks:
      - aidareu_network

  # Next.js Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: aidareu_frontend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_APP_URL: https://aidareu.com
      NEXT_PUBLIC_API_URL: https://api.aidareu.com
      NEXTAUTH_URL: https://aidareu.com
      NEXTAUTH_SECRET: YOUR_NEXTAUTH_SECRET_HERE
    depends_on:
      - backend
    networks:
      - aidareu_network

volumes:
  postgres_data:
    driver: local

networks:
  aidareu_network:
    driver: bridge
